data <- read.table(file = "household_power_consumption.txt", sep = ";", skip = 66637, nrows = 2880,header=TRUE)
names(data) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
data$Date<-as.Date(data$Date,format='%d/%m/%Y')
data$Time<-as.character(data$Time)
data$datetime<-as.POSIXct(paste(data$Date,data$Time))
with(data, plot(datetime,Global_active_power,col="black",ylab="Global Active Power (kilowatts)",xlab="Time",type="l"))
dev.copy(png,file="plot2.png",width = 480, height = 480)
dev.off()
